module

public import ThomGame.Analysis.CommutativeTorusFunctionalCalculus
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap

/-! The genuine closed algebra generated by a commuting unitary pair and its torus calculus. -/

@[expose] public noncomputable section
namespace ThomGame.Analysis

structure CommutingUnitaryPair (A : Type*) [CStarAlgebra A] where
  first : unitary A
  second : unitary A
  commutes : Commute (first : A) (second : A)

namespace CommutingUnitaryPair

open scoped IsMulCommutative
open IntegerTorus

variable {A : Type*} [CStarAlgebra A]

def algebra (p : CommutingUnitaryPair A) : StarSubalgebra ℂ A :=
  (StarAlgebra.adjoin ℂ {(p.first : A), (p.second : A)}).topologicalClosure

instance algebra_closed (p : CommutingUnitaryPair A) : IsClosed (algebra p : Set A) :=
  (StarAlgebra.adjoin ℂ {(p.first : A), (p.second : A)}).isClosed_topologicalClosure

instance algebra_commutative (p : CommutingUnitaryPair A) : IsMulCommutative (algebra p) := by
  let := CStarAlgebra.isMulCommutative_adjoin_pair p.commutes
  exact inferInstanceAs (IsMulCommutative
    (StarAlgebra.adjoin ℂ {(p.first : A), (p.second : A)}).topologicalClosure)

theorem first_mem_algebra (p : CommutingUnitaryPair A) : (p.first : A) ∈ algebra p :=
  StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin ℂ _ (by simp))

theorem second_mem_algebra (p : CommutingUnitaryPair A) : (p.second : A) ∈ algebra p :=
  StarSubalgebra.le_topologicalClosure _ (StarAlgebra.subset_adjoin ℂ _ (by simp))

def firstInAlgebra (p : CommutingUnitaryPair A) : unitary (algebra p) :=
  ⟨⟨p.first, first_mem_algebra p⟩,
    ⟨Subtype.ext p.first.property.1, Subtype.ext p.first.property.2⟩⟩

def secondInAlgebra (p : CommutingUnitaryPair A) : unitary (algebra p) :=
  ⟨⟨p.second, second_mem_algebra p⟩,
    ⟨Subtype.ext p.second.property.1, Subtype.ext p.second.property.2⟩⟩

def calculus (p : CommutingUnitaryPair A) : C(Torus, ℂ) →⋆ₐ[ℂ] A :=
  (algebra p).subtype.comp (torusFunctionalCalculus (firstInAlgebra p) (secondInAlgebra p))

theorem calculus_first (p : CommutingUnitaryPair A) :
    calculus p (coordinateCharacter false) = (p.first : A) := by
  change ((torusFunctionalCalculus (firstInAlgebra p) (secondInAlgebra p)
    (coordinateCharacter false) : algebra p) : A) = _
  rw [torusFunctionalCalculus_first]
  rfl

theorem calculus_second (p : CommutingUnitaryPair A) :
    calculus p (coordinateCharacter true) = (p.second : A) := by
  change ((torusFunctionalCalculus (firstInAlgebra p) (secondInAlgebra p)
    (coordinateCharacter true) : algebra p) : A) = _
  rw [torusFunctionalCalculus_second]
  rfl

theorem calculus_norm_le (p : CommutingUnitaryPair A) (f : C(Torus, ℂ)) :
    ‖calculus p f‖ ≤ ‖f‖ := NonUnitalStarAlgHom.norm_apply_le (calculus p) f

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

def ofIsometries (U V : H ≃ₗᵢ[ℂ] H) (h : Commute U V) : CommutingUnitaryPair (H →L[ℂ] H) where
  first := Unitary.linearIsometryEquiv.symm U
  second := Unitary.linearIsometryEquiv.symm V
  commutes := by
    apply ContinuousLinearMap.ext
    intro x
    exact congrArg (fun e : H ≃ₗᵢ[ℂ] H => e x) h.eq

theorem ofIsometries_calculus_first (U V : H ≃ₗᵢ[ℂ] H) (h : Commute U V) (x : H) :
    (ofIsometries U V h).calculus (coordinateCharacter false) x = U x := by
  rw [calculus_first]
  rfl

theorem ofIsometries_calculus_second (U V : H ≃ₗᵢ[ℂ] H) (h : Commute U V) (x : H) :
    (ofIsometries U V h).calculus (coordinateCharacter true) x = V x := by
  rw [calculus_second]
  rfl

end CommutingUnitaryPair
end ThomGame.Analysis
