module

public import ThomGame.Analysis.MatrixWOTTrace
public import ThomGame.Analysis.TraceFiniteness
public import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap

/-!
# The concrete finite operator algebra generated by the matrix quotient

The weak operator closed algebra is also closed in operator norm, hence
is a C-star algebra with its actual operator norm. Its normalized
faithful trace is the identity vector functional. Cyclicity and
faithfulness prove that every isometry in this algebra is unitary.
The original matrix quotient embeds faithfully and trace preservingly;
surjectivity of this embedding remains a separate question.
-/

@[expose] public section
namespace ThomGame.Analysis

open Filter
open scoped Topology

variable {ι : Type*} (dims : ι → Nat) (hd : ∀ i, 0 < dims i) (U : Ultrafilter ι)

noncomputable def matrixOperatorAlgebra :
    StarSubalgebra ℂ (MatrixTraceHilbert dims hd U →L[ℂ] MatrixTraceHilbert dims hd U) :=
  StarSubalgebra.comap (matrixOperatorToWOT dims hd U) (matrixWOTAlgebra dims hd U)

instance matrixOperatorAlgebra_isClosed : IsClosed (matrixOperatorAlgebra dims hd U :
    Set (MatrixTraceHilbert dims hd U →L[ℂ] MatrixTraceHilbert dims hd U)) :=
  (matrixWOTAlgebra_isClosed dims hd U).preimage ContinuousLinearMapWOT.continuous_ofCLM

noncomputable abbrev MatrixFiniteOperatorAlgebra := matrixOperatorAlgebra dims hd U

noncomputable def matrixOperatorClosureEquiv :
    MatrixFiniteOperatorAlgebra dims hd U ≃⋆ₐ[ℂ] MatrixWOTClosure dims hd U where
  toFun T := ⟨ContinuousLinearMapWOT.ofCLM T.val, T.property⟩
  invFun T := ⟨T.val.toCLM, T.property⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl
  map_add' _ _ := rfl
  map_star' _ := rfl
  map_smul' _ _ := rfl

theorem matrixOperatorClosureEquiv_continuous : Continuous (matrixOperatorClosureEquiv dims hd U) :=
  (ContinuousLinearMapWOT.continuous_ofCLM.comp continuous_subtype_val).subtype_mk _

noncomputable def matrixFiniteEmbedding :
    MatrixTracialQuotient dims (U : Filter ι) →⋆ₐ[ℂ] MatrixFiniteOperatorAlgebra dims hd U :=
  (matrixOperatorClosureEquiv dims hd U).symm.toStarAlgHom.comp (matrixWOTEmbedding dims hd U)

theorem matrixFiniteEmbedding_injective : Function.Injective (matrixFiniteEmbedding dims hd U) :=
  (matrixOperatorClosureEquiv dims hd U).symm.injective.comp (matrixWOTEmbedding_injective dims hd U)

noncomputable def matrixFiniteTrace : MatrixFiniteOperatorAlgebra dims hd U →L[ℂ] ℂ :=
  (matrixWOTTrace dims hd U).comp
    ⟨(matrixOperatorClosureEquiv dims hd U).toStarAlgHom.toAlgHom.toLinearMap,
      matrixOperatorClosureEquiv_continuous dims hd U⟩

@[simp] theorem matrixFiniteTrace_one : matrixFiniteTrace dims hd U 1 = 1 := by
  change matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U 1) = 1
  rw [map_one, matrixWOTTrace_one]

theorem matrixFiniteTrace_embedding (x : MatrixTracialQuotient dims (U : Filter ι)) :
    matrixFiniteTrace dims hd U (matrixFiniteEmbedding dims hd U x) = matrixUltratrace dims hd U x := by
  exact matrixWOTTrace_embedding dims hd U x

theorem matrixFiniteTrace_mul_comm (S T : MatrixFiniteOperatorAlgebra dims hd U) :
    matrixFiniteTrace dims hd U (S * T) = matrixFiniteTrace dims hd U (T * S) := by
  change matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U (S * T)) =
    matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U (T * S))
  rw [map_mul (matrixOperatorClosureEquiv dims hd U) S T,
    map_mul (matrixOperatorClosureEquiv dims hd U) T S, matrixWOTTrace_mul_comm]

theorem matrixFiniteTrace_star (T : MatrixFiniteOperatorAlgebra dims hd U) :
    matrixFiniteTrace dims hd U (star T) = star (matrixFiniteTrace dims hd U T) := by
  change matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U (star T)) = _
  rw [map_star, matrixWOTTrace_star]
  rfl

theorem matrixFiniteTrace_gram_nonneg (T : MatrixFiniteOperatorAlgebra dims hd U) :
    0 ≤ (matrixFiniteTrace dims hd U (star T * T)).re := by
  change 0 ≤ (matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U (star T * T))).re
  rw [map_mul, map_star]
  exact matrixWOTTrace_gram_nonneg dims hd U _

theorem matrixFiniteTrace_faithful (T : MatrixFiniteOperatorAlgebra dims hd U) :
    matrixFiniteTrace dims hd U (star T * T) = 0 ↔ T = 0 := by
  change matrixWOTTrace dims hd U (matrixOperatorClosureEquiv dims hd U (star T * T)) = 0 ↔ T = 0
  rw [map_mul, map_star, matrixWOTTrace_faithful]
  exact map_eq_zero_iff (matrixOperatorClosureEquiv dims hd U) (matrixOperatorClosureEquiv dims hd U).injective

theorem matrixFinite_isometry_unitary (T : MatrixFiniteOperatorAlgebra dims hd U)
    (hT : star T * T = 1) : T * star T = 1 :=
  mul_star_eq_one_of_faithful_trace (matrixFiniteTrace dims hd U).toLinearMap.toAddMonoidHom
    (matrixFiniteTrace_mul_comm dims hd U) (fun a => (matrixFiniteTrace_faithful dims hd U a).mp) T hT

theorem matrixFinite_mem_unitary_iff (T : MatrixFiniteOperatorAlgebra dims hd U) :
    T ∈ unitary (MatrixFiniteOperatorAlgebra dims hd U) ↔ star T * T = 1 := by
  constructor
  · exact fun h => h.1
  · exact fun h => ⟨h, matrixFinite_isometry_unitary dims hd U T h⟩

end ThomGame.Analysis
