module

public import ThomGame.Groups.FiniteCommutingClosure
public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.GroupTheory.Index

/-!
# Central commutators from genuine defining generators

If a set generates G and all generator commutators commute with the
generators, its commutator subgroup is central and is generated by those
actual commutators. Finite torsion generators then make G finite.
-/

@[expose] public section
namespace ThomGame

open scoped commutatorElement IsMulCommutative

variable {G : Type*} [Group G]

def generatorCommutators (S : Set G) : Set G := Set.range (fun a : S × S => ⁅a.1.val, a.2.val⁆)

def generatorCommutatorSubgroup (S : Set G) : Subgroup G := Subgroup.closure (generatorCommutators S)

theorem quotient_generators_generate {S : Set G} (hgen : Subgroup.closure S = ⊤)
    (N : Subgroup G) [N.Normal] :
    Subgroup.closure ((QuotientGroup.mk' N) '' S) = ⊤ := by
  rw [← MonoidHom.map_closure, hgen, Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective N)]

theorem quotient_commutes_of_generator_commutators {S : Set G} (hgen : Subgroup.closure S = ⊤)
    (N : Subgroup G) [N.Normal] (hN : ∀ x ∈ S, ∀ y ∈ S, ⁅x, y⁆ ∈ N) :
    IsMulCommutative (G ⧸ N) := by
  have hpair : ((QuotientGroup.mk' N) '' S).Pairwise Commute := by
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩ _
    apply commutatorElement_eq_one_iff_commute.mp
    rw [← map_commutatorElement, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
    exact hN x hx y hy
  let : IsMulCommutative (Subgroup.closure ((QuotientGroup.mk' N) '' S)) :=
    Subgroup.isMulCommutative_closure hpair
  apply IsMulCommutative.of_comm
  intro x y
  have hx : x ∈ Subgroup.closure ((QuotientGroup.mk' N) '' S) := by rw [quotient_generators_generate hgen]; trivial
  have hy : y ∈ Subgroup.closure ((QuotientGroup.mk' N) '' S) := by rw [quotient_generators_generate hgen]; trivial
  exact congrArg Subtype.val (mul_comm (⟨x, hx⟩ : Subgroup.closure ((QuotientGroup.mk' N) '' S)) ⟨y, hy⟩)

theorem generatorCommutatorSubgroup_le_center {S : Set G} (hgen : Subgroup.closure S = ⊤)
    (htriple : ∀ x ∈ S, ∀ y ∈ S, ∀ z ∈ S, Commute ⁅x, y⁆ z) :
    generatorCommutatorSubgroup S ≤ Subgroup.center G := by
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨⟨x, y⟩, rfl⟩
  rw [← Subgroup.centralizer_univ, ← Subgroup.coe_top, ← hgen, Subgroup.centralizer_closure]
  intro z hz
  exact (htriple x.val x.property y.val y.property z hz).eq.symm

theorem commutator_eq_generatorCommutatorSubgroup {S : Set G} (hgen : Subgroup.closure S = ⊤)
    (htriple : ∀ x ∈ S, ∀ y ∈ S, ∀ z ∈ S, Commute ⁅x, y⁆ z) :
    _root_.commutator G = generatorCommutatorSubgroup S := by
  let : (generatorCommutatorSubgroup S).Normal :=
    Subgroup.normal_of_le_center (generatorCommutatorSubgroup_le_center hgen htriple)
  apply le_antisymm
  · apply Subgroup.Normal.quotient_commutative_iff_commutator_le.mp
    apply quotient_commutes_of_generator_commutators hgen
    intro x hx y hy
    exact Subgroup.subset_closure ⟨(⟨x, hx⟩, ⟨y, hy⟩), rfl⟩
  · apply (Subgroup.closure_le _).mpr
    rintro _ ⟨⟨x, y⟩, rfl⟩
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _) (Subgroup.mem_top _)

theorem commutator_le_center_of_generators {S : Set G} (hgen : Subgroup.closure S = ⊤)
    (htriple : ∀ x ∈ S, ∀ y ∈ S, ∀ z ∈ S, Commute ⁅x, y⁆ z) :
    _root_.commutator G ≤ Subgroup.center G := by
  rw [commutator_eq_generatorCommutatorSubgroup hgen htriple]
  exact generatorCommutatorSubgroup_le_center hgen htriple

theorem generatorCommutatorSubgroup_finite {S : Set G} (hS : S.Finite)
    (hgen : Subgroup.closure S = ⊤)
    (htriple : ∀ x ∈ S, ∀ y ∈ S, ∀ z ∈ S, Commute ⁅x, y⁆ z)
    (p : Nat) (hp : 0 < p) (hpow : ∀ x ∈ S, x ^ p = 1) :
    Finite (generatorCommutatorSubgroup S) := by
  let : Finite S := hS.to_subtype
  have hC := generatorCommutatorSubgroup_le_center hgen htriple
  refine commutingClosure_finite (Set.finite_range _) ?_ p hp ?_
  · rintro x hx y hy _
    exact (Subgroup.mem_center_iff.mp (hC (Subgroup.subset_closure hx)) y).symm
  · rintro _ ⟨⟨x, y⟩, rfl⟩
    rw [(htriple x.val x.property y.val y.property x.val x.property).symm.commutatorElement_pow_left,
      hpow x.val x.property, commutatorElement_one_left]

theorem finite_of_central_commutator_generators {S : Set G} (hS : S.Finite)
    (hgen : Subgroup.closure S = ⊤)
    (htriple : ∀ x ∈ S, ∀ y ∈ S, ∀ z ∈ S, Commute ⁅x, y⁆ z)
    (p : Nat) (hp : 0 < p) (hpow : ∀ x ∈ S, x ^ p = 1) : Finite G := by
  let N := generatorCommutatorSubgroup S
  let : N.Normal := Subgroup.normal_of_le_center (generatorCommutatorSubgroup_le_center hgen htriple)
  let : Finite N := generatorCommutatorSubgroup_finite hS hgen htriple p hp hpow
  let : IsMulCommutative (G ⧸ N) := quotient_commutes_of_generator_commutators hgen N
    (fun x hx y hy => Subgroup.subset_closure ⟨(⟨x, hx⟩, ⟨y, hy⟩), rfl⟩)
  let : Finite (G ⧸ N) := finite_of_commuting_generators (hS.image (QuotientGroup.mk' N))
    (quotient_generators_generate hgen N) (fun _ _ _ _ _ => Commute.all _ _) p hp (by
      rintro _ ⟨x, hx, rfl⟩
      rw [← map_pow, hpow x hx, map_one])
  exact (Subgroup.finite_iff_finite_and_finiteIndex N).mpr
    ⟨inferInstance, Subgroup.finiteIndex_of_finite_quotient⟩

end ThomGame
