module

public import Mathlib.GroupTheory.HNNExtension
public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.Algebra.Group.Subgroup.Ker
public import Mathlib.Algebra.Group.TypeTags.Finite
public import Mathlib.Data.ZMod.Basic
public import Mathlib.Tactic.Group

/-!
# The HNN twist adjoining a central involution

For an infinite-order element w of G, the subgroup generated by (w,1)
and (1,J) in G × C₂ is Z × C₂. Its involutive automorphism sends
(w,1) to (w,J) and fixes (1,J). No property of G beyond the explicit
infinite-order hypothesis is assumed.
-/

@[expose] public section
namespace ThomGame.CentralTwist

abbrev C₂ := Multiplicative (ZMod 2)

def j : C₂ := Multiplicative.ofAdd 1

theorem j_ne_one : j ≠ 1 := by decide +kernel
theorem j_square : j * j = 1 := by decide +kernel
theorem c₂_cases : ∀ a : C₂, a = 1 ∨ a = j := by decide +kernel

abbrev Coordinates := Multiplicative ℤ × C₂

def parity (n : Multiplicative ℤ) : C₂ :=
  Multiplicative.ofAdd ((Multiplicative.toAdd n : ℤ) : ZMod 2)

theorem parity_mul (n m : Multiplicative ℤ) : parity (n * m) = parity n * parity m := by
  change (((Multiplicative.toAdd n + Multiplicative.toAdd m : ℤ) : ZMod 2)) = _
  exact Int.cast_add _ _

theorem parity_square (n : Multiplicative ℤ) : parity n * parity n = 1 := by
  have h : ∀ a : C₂, a * a = 1 := by decide +kernel
  exact h _

def coordinateTwist : Coordinates ≃* Coordinates where
  toFun a := (a.1, parity a.1 * a.2)
  invFun a := (a.1, parity a.1 * a.2)
  left_inv a := by ext <;> simp [← mul_assoc, parity_square]
  right_inv a := by ext <;> simp [← mul_assoc, parity_square]
  map_mul' a b := by
    apply Prod.ext
    · rfl
    · change parity (a.1 * b.1) * (a.2 * b.2) = (parity a.1 * a.2) * (parity b.1 * b.2)
      rw [parity_mul]
      ac_rfl

variable {G : Type*} [Group G]

theorem coordinates_hom_ext {φ ψ : Coordinates →* G}
    (hw : φ (Multiplicative.ofAdd 1, 1) = ψ (Multiplicative.ofAdd 1, 1))
    (hj : φ (1, j) = ψ (1, j)) : φ = ψ := by
  have hn : φ.comp (MonoidHom.inl _ _) = ψ.comp (MonoidHom.inl _ _) :=
    MonoidHom.ext_mint hw
  have hc : φ.comp (MonoidHom.inr _ _) = ψ.comp (MonoidHom.inr _ _) := by
    apply MonoidHom.ext
    intro c
    rcases c₂_cases c with rfl | rfl
    · change φ 1 = ψ 1
      simp
    · exact hj
  apply MonoidHom.ext
  rintro ⟨n, c⟩
  have he : (n, c) = (n, 1) * (1, c) := by simp
  rw [he, map_mul, map_mul]
  exact congrArg₂ (· * ·) (DFunLike.congr_fun hn n) (DFunLike.congr_fun hc c)

def involutionHom (a : G) (ha : a * a = 1) : C₂ →* G where
  toFun c := if c = 1 then 1 else a
  map_one' := by simp
  map_mul' c d := by
    rcases c₂_cases c with rfl | rfl <;> rcases c₂_cases d with rfl | rfl <;>
      simp [j_ne_one, j_square, ha]

theorem involutionHom_j (a : G) (ha : a * a = 1) : involutionHom a ha j = a := by
  simp [involutionHom, j_ne_one]

def coordinates (w : G) : Coordinates →* G × C₂ where
  toFun a := (w ^ Multiplicative.toAdd a.1, a.2)
  map_one' := by simp
  map_mul' a b := by ext <;> simp [zpow_add]

theorem coordinates_injective {w : G} (hw : ¬ IsOfFinOrder w) :
    Function.Injective (coordinates w) := by
  intro a b h
  apply Prod.ext
  · exact (injective_zpow_iff_not_isOfFinOrder.mpr hw) (congrArg Prod.fst h)
  · exact congrArg (fun p : G × C₂ => p.2) h

noncomputable def coordinateEquiv {w : G} (hw : ¬ IsOfFinOrder w) :
    Coordinates ≃* (coordinates w).range := MonoidHom.ofInjective (coordinates_injective hw)

noncomputable def twist {w : G} (hw : ¬ IsOfFinOrder w) :
    (coordinates w).range ≃* (coordinates w).range :=
  ((coordinateEquiv hw).symm.trans coordinateTwist).trans (coordinateEquiv hw)

theorem twist_coordinateEquiv {w : G} (hw : ¬ IsOfFinOrder w) (a : Coordinates) :
    twist hw (coordinateEquiv hw a) = coordinateEquiv hw (coordinateTwist a) := by
  simp [twist]

abbrev Extension {w : G} (hw : ¬ IsOfFinOrder w) :=
  HNNExtension (G × C₂) (coordinates w).range (coordinates w).range (twist hw)

noncomputable def base {w : G} (hw : ¬ IsOfFinOrder w) : G × C₂ →* Extension hw :=
  HNNExtension.of

noncomputable def stable {w : G} (hw : ¬ IsOfFinOrder w) : Extension hw := HNNExtension.t

theorem base_injective {w : G} (hw : ¬ IsOfFinOrder w) : Function.Injective (base hw) :=
  HNNExtension.of_injective (twist hw)

theorem base_j_square {w : G} (hw : ¬ IsOfFinOrder w) :
    base hw (1, j) * base hw (1, j) = 1 := by
  rw [← map_mul]
  have hp : ((1, j) : G × C₂) * (1, j) = 1 := by
    apply Prod.ext <;> simp [j_square]
  rw [hp, map_one]

theorem stable_coordinate {w : G} (hw : ¬ IsOfFinOrder w) (a : Coordinates) :
    stable hw * base hw (coordinates w a) * (stable hw)⁻¹ =
      base hw (coordinates w (coordinateTwist a)) := by
  have h := HNNExtension.equiv_eq_conj (φ := twist hw) (coordinateEquiv hw a)
  rw [twist_coordinateEquiv] at h
  exact h.symm

theorem stable_w {w : G} (hw : ¬ IsOfFinOrder w) :
    stable hw * base hw (w, 1) * (stable hw)⁻¹ = base hw (w, j) := by
  simpa [coordinates, coordinateTwist, parity, j] using
    stable_coordinate hw (Multiplicative.ofAdd 1, 1)

theorem stable_j {w : G} (hw : ¬ IsOfFinOrder w) :
    stable hw * base hw (1, j) * (stable hw)⁻¹ = base hw (1, j) := by
  simpa [coordinates, coordinateTwist, parity] using
    stable_coordinate hw (1, j)

theorem base_j_ne_one {w : G} (hw : ¬ IsOfFinOrder w) : base hw (1, j) ≠ 1 := by
  intro h
  have hp : (1, j) = (1 : G × C₂) := base_injective hw (h.trans (map_one _).symm)
  exact j_ne_one (congrArg Prod.snd hp)

end ThomGame.CentralTwist
