module

public import ThomGame.Groups.CompressorPresentation
public import ThomGame.Finite.PresentedWords
public import ThomGame.Finite.WordHom
public import Mathlib.Algebra.Group.Subgroup.Lattice

/-! The compressor quotient and its subgroup generated by positive labels. -/

@[expose] public section
namespace ThomGame.Compressor

def ofGenerator (g : Generator) : GroupQ := PresentedGroup.of g

def hElement : GroupQ := ofGenerator (.inl (root12, some (1, true)))
def tElement : GroupQ := ofGenerator (.inr root12)
def backwardConjugate : GroupQ := tElement⁻¹ * hElement * tElement

/-- The constant and the three positive variable labels, for each root.
An inverse letter in a word does not change whether its generator is positive. -/
def positive : Generator → Bool
  | .inl (_, none) => true
  | .inl (_, some (_, b)) => b
  | .inr _ => false

def positiveSubgroup : Subgroup GroupQ :=
  Subgroup.closure (ofGenerator '' {g | positive g = true})

theorem ofGenerator_mem_positiveSubgroup (g : Generator) (hg : positive g = true) :
    ofGenerator g ∈ positiveSubgroup := Subgroup.subset_closure ⟨g, hg, rfl⟩

theorem h_mem_positiveSubgroup : hElement ∈ positiveSubgroup :=
  ofGenerator_mem_positiveSubgroup _ rfl

theorem positive_generator_count : Fintype.card {g : Generator // positive g = true} = 24 := by
  decide +kernel

theorem eval_rawRelator (r : Word Generator) (hr : r ∈ rawRelators) :
    Word.eval ofGenerator r = 1 := by
  change Word.eval (PresentedGroup.of (rels := relators)) r = 1
  rw [Word.eval_presented]
  exact PresentedGroup.one_of_mem ⟨r, hr, rfl⟩

theorem generated_by (K : Subgroup GroupQ)
    (hK : ∀ g, ofGenerator g ∈ K) (x : GroupQ) : x ∈ K :=
  PresentedGroup.generated_by relators K hK x

theorem hom_agree_on_positive {G : Type*} [Group G] (φ ψ : GroupQ →* G)
    (h : ∀ g, positive g = true → φ (ofGenerator g) = ψ (ofGenerator g))
    (x : positiveSubgroup) : φ x = ψ x := by
  have he : positiveSubgroup ≤ φ.eqLocus ψ := by
    apply (Subgroup.closure_le (φ.eqLocus ψ)).mpr
    rintro _ ⟨g, hg, rfl⟩
    exact h g hg
  exact he x.property

end ThomGame.Compressor
