module

public import ThomGame.Pictures.GraphRotation
public import ThomGame.Pictures.RibbonConnectivity
public import ThomGame.Pictures.BoundaryReturn

/-!
# Actual graph paths and the permutation component quotient

Paths use the real edge incidences and may pass through relation hubs.
The relation is defined on all vertices, including isolated zero-port
hubs. For vertices carrying darts, it agrees exactly with connectivity
generated by edge reversal and circuit successor.
-/

@[expose] public section
namespace ThomGame.Pictures.PortGraph

open Equiv

variable {R S : Type*} {P : InvolutionPresentation R S} {u v : List S} (G : PortGraph P u v)

def Reachable : G.Vertex → G.Vertex → Prop := Relation.ReflTransGen G.Adj

theorem reachable_refl (x : G.Vertex) : G.Reachable x x := Relation.ReflTransGen.refl

theorem reachable_symm {x y : G.Vertex} (h : G.Reachable x y) : G.Reachable y x := by
  induction h with
  | refl => exact G.reachable_refl _
  | tail _ hxy ih => exact (Relation.ReflTransGen.single (G.adj_symm hxy)).trans ih

theorem reachable_trans {x y z : G.Vertex} (h : G.Reachable x y) (k : G.Reachable y z) :
    G.Reachable x z := h.trans k

theorem reachable_edge (a : G.Dart) : G.Reachable a.vertex (G.pairing.twin a).vertex :=
  Relation.ReflTransGen.single ⟨a, rfl, rfl⟩

theorem reachable_circuit (a : G.Dart) : G.Reachable a.vertex (G.circuitStep a).vertex :=
  Relation.ReflTransGen.single (G.adj_circuitStep a)

theorem connected_vertex_reachable {a b : G.Dart}
    (h : RibbonConnectivity.Connected G.pairing.perm G.circuitStep a b) :
    G.Reachable a.vertex b.vertex :=
  h.lift Port.vertex ⟨G.reachable_refl, G.reachable_symm, G.reachable_trans⟩
    G.reachable_edge G.reachable_circuit

theorem connected_rotation (a : G.Dart) :
    RibbonConnectivity.Connected G.pairing.perm G.circuitStep a (G.rotation a) := by
  have h := (RibbonConnectivity.Connected.edge (p := G.pairing.perm) (f := G.circuitStep) a).trans
    (RibbonConnectivity.Connected.circuit (G.pairing.twin a))
  change RibbonConnectivity.Connected G.pairing.perm G.circuitStep a
    (G.rotation (G.pairing.twin (G.pairing.twin a))) at h
  rw [G.pairing.involutive] at h
  exact h

theorem connected_of_same_vertex {a b : G.Dart} (hab : a.vertex = b.vertex) :
    RibbonConnectivity.Connected G.pairing.perm G.circuitStep a b := by
  obtain ⟨n, rfl⟩ := ((G.rotation_sameCycle_iff a b).mpr hab).exists_nat_pow_eq
  clear hab
  induction n with
  | zero => exact RibbonConnectivity.Connected.refl _
  | succ n ih =>
    rw [pow_succ', Perm.mul_apply]
    exact ih.trans (G.connected_rotation _)

theorem reachable_connects_darts {x y : G.Vertex} (h : G.Reachable x y)
    (a b : G.Dart) (ha : a.vertex = x) (hb : b.vertex = y) :
    RibbonConnectivity.Connected G.pairing.perm G.circuitStep a b := by
  induction h generalizing b with
  | refl => exact G.connected_of_same_vertex (ha.trans hb.symm)
  | @tail y z hxy hyz ih =>
    obtain ⟨c, hc, hd⟩ := hyz
    exact (ih c hc).trans ((RibbonConnectivity.Connected.edge c).trans
      (G.connected_of_same_vertex (hd.trans hb.symm)))

theorem connected_iff_vertex_reachable (a b : G.Dart) :
    RibbonConnectivity.Connected G.pairing.perm G.circuitStep a b ↔
      G.Reachable a.vertex b.vertex :=
  ⟨G.connected_vertex_reachable, fun h => G.reachable_connects_darts h a b rfl rfl⟩

theorem circuit_sameCycle_reachable {a b : G.Dart} (h : G.circuitStep.SameCycle a b) :
    G.Reachable a.vertex b.vertex :=
  G.connected_vertex_reachable (RibbonConnectivity.sameCycle_connected G.pairing.perm G.circuitStep h)

theorem boundary_sameCycle_reachable {a b : BoundaryIndex u v}
    (h : G.boundaryNext.SameCycle a b) : G.Reachable (G.boundaryVertex a) (G.boundaryVertex b) := by
  have hc := (G.boundaryNext_sameCycle_iff a b).mp h
  have hr := G.circuit_sameCycle_reachable ((G.circuit_eq_iff _ _).mp hc)
  cases a <;> cases b <;> exact hr

end ThomGame.Pictures.PortGraph
