module

public import ThomGame.Pictures.PermutationSurgery
public import Mathlib.Logic.Relation

/-!
# Connectivity generated by edge reversal and circuit successor

For a port graph these two permutations generate the same connectivity
as crossing edges and turning through vertices. Here the equivalence
closure and its component quotient are defined without a planar premise.
-/

@[expose] public section
namespace ThomGame.Pictures.RibbonConnectivity

open Equiv

variable {A B C : Type*}

def Step (p f : Perm A) (x y : A) : Prop := y = p x ∨ y = f x

def Connected (p f : Perm A) : A → A → Prop := Relation.EqvGen (Step p f)

namespace Connected

variable {p f : Perm A} {x y z : A}

theorem refl (x : A) : Connected p f x x := Relation.EqvGen.refl _

theorem edge (x : A) : Connected p f x (p x) := Relation.EqvGen.rel _ _ (Or.inl rfl)

theorem circuit (x : A) : Connected p f x (f x) := Relation.EqvGen.rel _ _ (Or.inr rfl)

theorem symm (h : Connected p f x y) : Connected p f y x := Relation.EqvGen.symm _ _ h

theorem trans (h : Connected p f x y) (k : Connected p f y z) : Connected p f x z :=
  Relation.EqvGen.trans _ _ _ h k

theorem lift {r : B → B → Prop} (e : A → B)
    (hr : Equivalence r) (hp : ∀ x, r (e x) (e (p x))) (hf : ∀ x, r (e x) (e (f x)))
    (h : Connected p f x y) : r (e x) (e y) := by
  induction h with
  | rel x y h => rcases h with rfl | rfl; exact hp x; exact hf x
  | refl x => exact hr.refl _
  | symm _ _ _ ih => exact hr.symm ih
  | trans _ _ _ _ _ ih ik => exact hr.trans ih ik

theorem map {q g : Perm B} (e : A → B)
    (hp : ∀ x, q (e x) = e (p x)) (hf : ∀ x, g (e x) = e (f x))
    (h : Connected p f x y) : Connected q g (e x) (e y) := by
  apply h.lift e ⟨Connected.refl, Connected.symm, Connected.trans⟩
  · intro x
    rw [← hp]
    exact Connected.edge _
  · intro x
    rw [← hf]
    exact Connected.circuit _

theorem invariant (q : A → C) (hp : ∀ x, q (p x) = q x) (hf : ∀ x, q (f x) = q x)
    (h : Connected p f x y) : q x = q y :=
  h.lift q ⟨Eq.refl, Eq.symm, Eq.trans⟩ (fun x => (hp x).symm) (fun x => (hf x).symm)

end Connected

theorem connected_congr (p f : Perm A) (q g : Perm B) (e : A ≃ B)
    (hp : ∀ x, q (e x) = e (p x)) (hf : ∀ x, g (e x) = e (f x)) (x y : A) :
    Connected p f x y ↔ Connected q g (e x) (e y) := by
  constructor
  · exact Connected.map e hp hf
  · intro h
    have hp' : ∀ x, p (e.symm x) = e.symm (q x) := by
      intro x
      simpa only [e.apply_symm_apply, e.symm_apply_apply] using
        (congrArg e.symm (hp (e.symm x))).symm
    have hf' : ∀ x, f (e.symm x) = e.symm (g x) := by
      intro x
      simpa only [e.apply_symm_apply, e.symm_apply_apply] using
        (congrArg e.symm (hf (e.symm x))).symm
    simpa only [e.symm_apply_apply] using h.map e.symm hp' hf'

theorem sameCycle_connected [Finite A] (p f : Perm A) {x y : A} (h : f.SameCycle x y) :
    Connected p f x y := by
  obtain ⟨n, rfl⟩ := h.exists_nat_pow_eq
  clear h
  induction n with
  | zero => exact Connected.refl _
  | succ n ih =>
    rw [pow_succ', Perm.mul_apply]
    exact ih.trans (Connected.circuit _)

def componentSetoid (p f : Perm A) : Setoid A := Relation.EqvGen.setoid (Step p f)

def Component (p f : Perm A) := Quotient (componentSetoid p f)

instance [Finite A] (p f : Perm A) : Finite (Component p f) := by
  unfold Component
  infer_instance

def component (p f : Perm A) (x : A) : Component p f := Quotient.mk _ x

theorem component_eq_iff (p f : Perm A) (x y : A) :
    component p f x = component p f y ↔ Connected p f x y := Quotient.eq

theorem component_edge (p f : Perm A) (x : A) : component p f (p x) = component p f x :=
  (component_eq_iff p f _ _).mpr (Connected.edge x).symm

theorem component_circuit (p f : Perm A) (x : A) : component p f (f x) = component p f x :=
  (component_eq_iff p f _ _).mpr (Connected.circuit x).symm

end ThomGame.Pictures.RibbonConnectivity
